services:
  backend:
    restart: always
    image: ghcr.io/star-academy/summer1403-devops-team12/traceroute-api

    environment:
      - REDIS_CONN_STR=redis://database:6379

    ports:
      - "9123:8080"

    depends_on:
      database:
        condition: service_healthy

  database:
    restart: always
    image: redis:7.4-alpine

    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

    volumes:
      - redis-data:/data

    command:
      [
        "redis-server",
        "--save",
        "60",
        "1",
        "--loglevel",
        "warning"
      ]

volumes:
  redis-data: {}
