apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: traceroute
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "2"
    limits.memory: "6Gi"
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"
