apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: traceroute
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/redis
